### ISSUE TITLE
Add livenessProbe and readinessProbe endpoints

### ISSUE THREAD

**Issue by andrewsgreene** [defenseunicorns/baffles-api#3]
**Describe the solution you'd like**
Leverage Kubernetes mechanics, by implementing the liveness and readiness endpoints.

sample helm chart updates
```
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
```
